### ISSUE TITLE
动态口令是否支持其它方式 

### ISSUE THREAD

**Issue by zhaodatou** [baoleiji/QlinBaoleiji#2]
楼主，用了一下您的堡垒机50点免费版本，感觉不错，不过有一个问题，我们有一些非州用户，没有安卓手机，是否有其它方式的动态口令提供，比如短信、软件令牌，谢谢！

**Comment by baoleiji** [comment]
您的版本太老了，最新版本支持软件令牌，即可以直接在windows上运行一个软件产生动态口令，您可以直接从官网上下载更新
