### ISSUE TITLE
另外还有二个问题我一个一个说，双机不能同步问题

### ISSUE THREAD

**Issue by zhaodatou** [baoleiji/QlinBaoleiji#3]
我们启用了堡垒机双机，但是录相不能同步，配置文件参数都可以同步，这个要做什么配置吗？

**Comment by baoleiji** [comment]
双机环境支持录相同步，请查看crontab -l，把那个backup_sessions的程序执行权限设置为755，旧的版本有这个BUG，如果新版本程序安装时会自动设置
