### ISSUE TITLE
第三个问题，堡垒机内置的SSL VPN是否可以用于直接连接内网服务器

### ISSUE THREAD

**Issue by zhaodatou** [baoleiji/QlinBaoleiji#4]
我们有一些需求，想要连接内网的服务器应用（不需要过堡垒机审计），比如一些OA的业务，这个堡垒机内置的SSL VPN是否可以支持？

**Comment by baoleiji** [comment]
可以，到VPN菜单发布 VPN路由，您到官网查看手册上面有
