### ISSUE TITLE
现在MYSQL和ORACLE应用发布的审计出不来SQL，只能录相是怎么回事

### ISSUE THREAD

**Issue by ying1000** [baoleiji/QlinBaoleiji#7]
楼主，我用应用发布的时候，MYSQL工具navacate，oracle工具plsql，只能录相，没有分离出SQL语句，这样检索太麻烦了，请问要什么配置 吗

**Comment by baoleiji** [comment]
数据库审计需要应用发布的组件安装特定的客户端版本，在手册中有描述，如果您直接从网上下载一些绿色的软件，有可能会无法分离出SQL
